[versions]
agp = "9.0.0"
maven-publish = "0.36.0"
kotlin = "2.3.0"
lifecycle-service = "2.10.0"
logback-android = "3.0.0"
conscrypt-android = "2.5.3"
core-ktx = "1.17.0"
kotlinx-coroutines-android = "1.10.2"
lifecycle-runtime-ktx = "2.10.0"
accompanist-permissions = "0.37.3"
compose-bom = "2026.01.00"
compose-activity = "1.12.2"
compose-ui = "1.10.1"
material3 = "1.7.8"
material-icons-extended = "1.7.8"
appwidget-preview = "0.1.2"
appwidget-host = "0.2.2"
bcprov-jdk18on = "1.83"
camera-camera2 = "1.5.2"
glance = "1.1.1"
gson = "2.13.2"
koog-agents = "0.6.0"
onnx-runtime-android = "1.16.3" # do not change, new version does not work
slf4j-api = "2.0.17"
stream-webrtc-android = "1.3.10"
media3 = "1.9.0"
ktor = "3.4.0"
okhttp = "5.3.2"
kodein = "7.30.0"
palette-ktx = "1.0.0"
vosk-android="0.3.75"

[libraries]
# base
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle-service" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logback-android" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
# glance
androidx-glance = { module = "androidx.glance:glance", version.ref = "glance" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-material = { module = "androidx.glance:glance-material", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
androidx-glance-preview = { module = "androidx.glance:glance-preview", version.ref = "glance" }
androidx-glance-appwidget-preview = { module = "androidx.glance:glance-appwidget-preview", version.ref = "glance" }
appwidget-host = { module = "com.google.android.glance.tools:appwidget-host", version.ref = "appwidget-host" }
appwidget-viewer = { module = "com.google.android.glance.tools:appwidget-viewer", version.ref = "appwidget-host" }
appwidget-preview = { module = "com.google.android.glance.tools:appwidget-preview", version.ref = "appwidget-preview" }
# media
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-media3-ui-compose = { module = "androidx.media3:media3-ui-compose", version.ref = "media3" }
# compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
# camera
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera-camera2" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera-camera2" }
# other
bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcprov-jdk18on" }
bctls-jdk18on = { module = "org.bouncycastle:bctls-jdk18on", version.ref = "bcprov-jdk18on" }
conscrypt-android = { module = "org.conscrypt:conscrypt-android", version.ref = "conscrypt-android" }
# json
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
# ai
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog-agents" }
onnxruntime-android = { module = "com.microsoft.onnxruntime:onnxruntime-android", version.ref = "onnx-runtime-android" }
vosk-android = { module = "com.alphacephei:vosk-android", version.ref="vosk-android" }
# ktor
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cio= { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor" }
# net todo : remove
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
# webrtc
stream-webrtc-android = { module = "io.getstream:stream-webrtc-android", version.ref = "stream-webrtc-android" }
# di
kodein-di = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
kodein-di-framework-compose = { module = "org.kodein.di:kodein-di-framework-compose", version.ref = "kodein" }
# palette
androidx-palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette-ktx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
